------------------------------------------------------/ DESAFIOS /--------------------------------------------------------

-- 1)
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao'
SELECT TOP 5 * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC
/*
SELECT	CODIGO_DO_PRODUTO, MAX(QUANTIDADE) AS [QUANTIDADE MAX], MIN(QUANTIDADE) AS [QUANTIDADE MIN]
FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' GROUP BY CODIGO_DO_PRODUTO 
*/


SELECT	CODIGO_DO_PRODUTO,
		COUNT(QUANTIDADE) AS [VENDAS FEITAS COM QUANTIDADE 99]
FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99
GROUP BY CODIGO_DO_PRODUTO


SELECT	NOME, LIMITE_DE_CREDITO,
		(CASE 
			WHEN LIMITE_DE_CREDITO > 150000 THEN 'Cliente Grande'
			WHEN LIMITE_DE_CREDITO BETWEEN 110000 AND 150000 THEN 'Cliente Médio'
			ELSE 'Cliente Pequeno'
		END) [CLASSIFICACAO]
FROM TABELA_DE_CLIENTES

SELECT	COUNT(*) [QUANTIDADE DE CLIENTES], 
		(CASE 
			WHEN LIMITE_DE_CREDITO > 150000 THEN 'Cliente Grande'
			WHEN LIMITE_DE_CREDITO BETWEEN 110000 AND 150000 THEN 'Cliente Médio'
			ELSE 'Cliente Pequeno'
		END) [CLASSIFICACAO]
FROM TABELA_DE_CLIENTES
GROUP BY (CASE 
			WHEN LIMITE_DE_CREDITO > 150000 THEN 'Cliente Grande'
			WHEN LIMITE_DE_CREDITO BETWEEN 110000 AND 150000 THEN 'Cliente Médio'
			ELSE 'Cliente Pequeno'
		 END)


SELECT * FROM TABELA_DE_PRODUTOS

SELECT	NF.CODIGO_DO_PRODUTO, 
		PROD.NOME_DO_PRODUTO,
		SUM(NF.QUANTIDADE) AS [QUANTIDADE DE VENDA DOS ITENS]
FROM ITENS_NOTAS_FISCAIS AS [NF]
		INNER JOIN TABELA_DE_PRODUTOS AS [PROD] 
		ON NF.CODIGO_DO_PRODUTO = PROD.CODIGO_DO_PRODUTO
GROUP BY PROD.NOME_DO_PRODUTO, NF.CODIGO_DO_PRODUTO
HAVING SUM(NF.QUANTIDADE) >= 394000 
ORDER BY SUM(NF.QUANTIDADE) DESC


SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO 
		IN (SELECT NF.CODIGO_DO_PRODUTO 
			FROM ITENS_NOTAS_FISCAIS [NF]
				INNER JOIN TABELA_DE_PRODUTOS [PROD]
				ON NF.CODIGO_DO_PRODUTO = PROD.CODIGO_DO_PRODUTO 
				GROUP BY NF.CODIGO_DO_PRODUTO
				HAVING SUM(QUANTIDADE) > 394000)


CREATE VIEW VW_QUANTIDADE_PRODUTOS AS
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO;

SELECT * FROM VW_QUANTIDADE_PRODUTOS
WHERE QUANTIDADE_TOTAL > 394000 
ORDER BY QUANTIDADE_TOTAL DESC;

--------------------------------------------------------------------------------------------------------------------------
--IDADE = 17
--FORMADO = 'Inglês'
--
--(IDADE >= 18 OR FORMADO = 'Inglês' >> Escola Astronomicos) OR (IDADE < 18 AND FORMADO = 'Alemão' >> Escola Supersonicos)
--									 (FALSO OR VERDADEIRO) OR (VERDADEIRO AND FALSO)
--											  (VERDADEIRO) OR (FALSO)
--													  (VERDADEIRO)