------------------------------ Vendas Válidas ------------------------------

SELECT
	NF.CPF,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO,
	SUM(IT.QUANTIDADE) AS [QUANTIDADE TOTAL DE COMPRAS]
FROM
	NOTAS_FISCAIS NF (NOLOCK)
	INNER JOIN ITENS_NOTAS_FISCAIS IT
		ON NF.NUMERO = IT.NUMERO
GROUP BY
	NF.CPF,
	CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
ORDER BY 2 ASC


SELECT
	TC.CPF,
	TC.NOME,
	TC.VOLUME_DE_COMPRA AS [VOLUME MAX DE COMPRAS],
	TV.MES_ANO,
	TV.[QUANTIDADE TOTAL DE COMPRAS],
	(CASE 
		WHEN TC.VOLUME_DE_COMPRA >= TV.[QUANTIDADE TOTAL DE COMPRAS] THEN 'Vendas Válidas'
		ELSE 'Vendas Inválidas'
	END) AS RESULTADO
FROM 
	TABELA_DE_CLIENTES TC
	INNER JOIN (
		SELECT
			NF.CPF,
			CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO,
			SUM(IT.QUANTIDADE) AS [QUANTIDADE TOTAL DE COMPRAS]
		FROM
			NOTAS_FISCAIS NF (NOLOCK)
			INNER JOIN ITENS_NOTAS_FISCAIS IT
				ON NF.NUMERO = IT.NUMERO
		GROUP BY
			NF.CPF,
			CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
	) AS TV
		ON TV.CPF = TC.CPF
WHERE 
	TV.MES_ANO = '2015-01'




SELECT
	TP.SABOR,
	YEAR(NF.DATA_VENDA) AS ANO,
	SUM(IT.QUANTIDADE) AS VENDA_ANO
FROM 
	TABELA_DE_PRODUTOS TP
	INNER JOIN ITENS_NOTAS_FISCAIS IT
		ON TP.CODIGO_DO_PRODUTO = IT.CODIGO_DO_PRODUTO
	INNER JOIN NOTAS_FISCAIS NF
		ON IT.NUMERO = NF.NUMERO
WHERE
	YEAR(NF.DATA_VENDA) = 2015
GROUP BY
	TP.SABOR,
	YEAR(NF.DATA_VENDA)
ORDER BY SUM(IT.QUANTIDADE) DESC


SELECT
	YEAR(NF.DATA_VENDA) AS ANO,
	SUM(IT.QUANTIDADE) AS VENDA_TOTAL_ANO
FROM
	NOTAS_FISCAIS NF
	INNER JOIN ITENS_NOTAS_FISCAIS IT
		ON NF.NUMERO = IT.NUMERO
WHERE
	YEAR(NF.DATA_VENDA) = 2015
GROUP BY
	YEAR(NF.DATA_VENDA)



SELECT
	VS.SABOR,
	VA.ANO,
	VS.VENDA_ANO,
	VA.VENDA_TOTAL_ANO,
	ROUND((CONVERT(FLOAT, VS.VENDA_ANO) / CONVERT(FLOAT, VA.VENDA_TOTAL_ANO)) * 100, 2) AS PORCENTUAL
FROM (
	SELECT
		TP.SABOR,
		YEAR(NF.DATA_VENDA) AS ANO,
		SUM(IT.QUANTIDADE) AS VENDA_ANO
	FROM 
		TABELA_DE_PRODUTOS TP
		INNER JOIN ITENS_NOTAS_FISCAIS IT
			ON TP.CODIGO_DO_PRODUTO = IT.CODIGO_DO_PRODUTO
		INNER JOIN NOTAS_FISCAIS NF
			ON IT.NUMERO = NF.NUMERO
	WHERE
		YEAR(NF.DATA_VENDA) = 2015
	GROUP BY
		TP.SABOR,
		YEAR(NF.DATA_VENDA)
	) AS VS
		INNER JOIN (
			SELECT
				YEAR(NF.DATA_VENDA) AS ANO,
				SUM(IT.QUANTIDADE) AS VENDA_TOTAL_ANO
			FROM
				NOTAS_FISCAIS NF
				INNER JOIN ITENS_NOTAS_FISCAIS IT
					ON NF.NUMERO = IT.NUMERO
			WHERE
				YEAR(NF.DATA_VENDA) = 2015
			GROUP BY
				YEAR(NF.DATA_VENDA)
		) AS VA
			ON VS.ANO = VA.ANO
ORDER BY VS.VENDA_ANO DESC