------------------------------ Funções de Conversão ------------------------------

SELECT CONVERT(varchar(10), getdate(), 121)
SELECT CONVERT(varchar(25), getdate(), 121)


SELECT 
	DATA_DE_NASCIMENTO, 
	CONVERT(varchar(25), DATA_DE_NASCIMENTO, 121)
FROM 
	TABELA_DE_CLIENTES


SELECT 
	DATA_DE_NASCIMENTO, 
	CONVERT(varchar(25), DATA_DE_NASCIMENTO, 106)
FROM 
	TABELA_DE_CLIENTES


SELECT
	NOME_DO_PRODUTO,
	CONCAT('O preço de lista é: ', CAST(PRECO_DE_LISTA AS VARCHAR(10))) AS [PREÇO]
FROM 
	TABELA_DE_PRODUTOS

/* DESAFIO */
SELECT
	TC.NOME,
	CONCAT(	'O cliente ', TC.NOME, 
			' comprou R$ ', TRIM(STR(SUM(IT.QUANTIDADE * IT.PRECO) ,10 , 2)),
			' no ano de ', YEAR(NF.DATA_VENDA), '.') AS [VALOR]
FROM 
	NOTAS_FISCAIS AS [NF] (NOLOCK)
		INNER JOIN ITENS_NOTAS_FISCAIS AS [IT] 
			ON NF.NUMERO = IT.NUMERO
		INNER JOIN TABELA_DE_CLIENTES AS [TC]
			ON NF.CPF = TC.CPF
WHERE
	YEAR(NF.DATA_VENDA) = '2016'
GROUP BY
	TC.NOME,
	YEAR(NF.DATA_VENDA)
