--DROP TABLE [dbo].[TABELA_TESTE]
--CREATE TABLE TABELA_TESTE (
--	ID VARCHAR(10)
--)


IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL -- Se a TABELA_TESTE existir, exclua a mesma

	DROP TABLE [SUCOS_VENDAS].[dbo].[TABELA_TESTE]
	PRINT 'Tabela excluída'


IF OBJECT_ID('TABELA_TESTE', 'U') IS NULL -- Se a TABELA_TESTE não existir, crie a mesma

	CREATE TABLE TABELA_TESTE (
		ID INT IDENTITY(1,1) NOT NULL,
		NOME VARCHAR(50) NOT NULL,
		IDADE INT NOT NULL,
		FORMADO_ALEMAO BIT,
		FORMADO_INGLES BIT
	)
	PRINT 'Tabela criada'



/* Desafio */
INSERT INTO [SUCOS_VENDAS].[dbo].[TABELA_TESTE] 
(NOME, IDADE, FORMADO_ALEMAO, FORMADO_INGLES)
	VALUES 
		 ('Eliane Barbosa', 20, 1, 0),
		 ('Ângela de Carvalho', 16, 1, 0),
		 ('Leonardo Bezerra', 25, 0, 0),
		 ('Marcos Machado', 22, 0, 1),
		 ('Mariana de Oliveira', 18, 1, 1) 


DECLARE @ID INT,
		@NOME_ALUNO VARCHAR(50),
		@IDADE_ALUNO INT,
		@FORMADO_INGLES BIT,
		@FORMADO_ALEMAO BIT
SET @ID = 1
SELECT @NOME_ALUNO = NOME,
		@IDADE_ALUNO = IDADE,
		@FORMADO_INGLES = FORMADO_INGLES,
		@FORMADO_ALEMAO = FORMADO_ALEMAO
FROM [SUCOS_VENDAS].[dbo].[TABELA_TESTE]
WHERE ID = @ID
PRINT CONCAT(
				@NOME_ALUNO, ' | ', 
				CAST(@IDADE_ALUNO AS VARCHAR(10)), ' | ',
				CAST(@FORMADO_ALEMAO AS VARCHAR(10)), ' | ',
				CAST(@FORMADO_INGLES AS VARCHAR(10))
			)

IF ((@IDADE_ALUNO >= 18 OR @FORMADO_INGLES = 1) OR (@IDADE_ALUNO < 18 AND @FORMADO_ALEMAO = 1))

	PRINT 'EXPRESSÃO VERDADEIRA'

ELSE

	PRINT 'EXPRESSÃO FALSA'