--SELECT GETDATE()

--SELECT DATENAME(WEEKDAY, GETDATE())

--SELECT GETDATE(), DATEADD(DAY, 5, GETDATE())

--SELECT DATENAME(WEEKDAY, DATEADD(DAY, 5, GETDATE()))

DECLARE @DIA_SEMANA VARCHAR(20),
		@NUMERO_DIAS INT 
SET @NUMERO_DIAS = 0
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()))
PRINT @DIA_SEMANA

IF @DIA_SEMANA = 'Domingo' OR @DIA_SEMANA = 'Sábado'

	PRINT 'Fim de Semana'

ELSE
	
	PRINT 'Dia de semana'



/* Desafio */
DECLARE @CPF VARCHAR(15),
		@DATA_NASCIMENTO DATE,
		@IDADE INT,
		@IDADE_TB INT
SET @CPF = '1471156710'
SELECT	@DATA_NASCIMENTO = [DATA DE NASCIMENTO],
		@IDADE_TB = IDADE 
FROM [SUCOS_VENDAS].dbo.[TABELA DE CLIENTES]
WHERE CPF = @CPF
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE())
IF @IDADE <> @IDADE_TB
UPDATE [SUCOS_VENDAS].dbo.[TABELA DE CLIENTES]
SET IDADE = @IDADE
WHERE CPF = @CPF