--SELECT * FROM [TABELA DE CLIENTES]

--SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY BAIRRO

--DECLARE @LIMIT_MAX FLOAT,
--		@LIMIT_ATUAL FLOAT,
--		@BAIRRO VARCHAR(20)
--SET @LIMIT_MAX = 50000
--SET @BAIRRO = 'Água Santa'

--SELECT @LIMIT_ATUAL = SUM([LIMITE DE CREDITO])
--FROM [TABELA DE CLIENTES]
--WHERE BAIRRO = @BAIRRO

--IF @LIMIT_MAX <= @LIMIT_ATUAL

--	PRINT 'Valor estourou'

--ELSE

--	PRINT 'Valor não estourou'

DECLARE @LIMIT_MAX FLOAT,
		@BAIRRO VARCHAR(20)
SET @LIMIT_MAX = 50000
SET @BAIRRO = 'Água Santa'

IF @LIMIT_MAX <=(SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO)

	PRINT 'Valor estourou'

ELSE

	PRINT 'Valor não estourou'



/* Desafio */
DECLARE @CPF VARCHAR(15);
DECLARE @DATA_NASCIMENTO DATE;
DECLARE @IDADE INT;
SET @CPF = '1471156710';
SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());
IF (SELECT COUNT(*) FROM  [TABELA DE CLIENTES] WHERE CPF = @CPF AND IDADE <> @IDADE) = 1 
    UPDATE [TABELA DE CLIENTES] SET IDADE = @IDADE WHERE CPF = @CPF;