-- # Vale para conexão vigente
-- ## Vale para várias conexões
-- @ Vale para o procedimento que eestá sendo executado

CREATE TABLE #TABELA01 (
	ID VARCHAR(10),
	NOME VARCHAR(10)
)

INSERT INTO #TABELA01
VALUES ('1', 'JOÃO')

SELECT * FROM #TABELA01

---------

CREATE TABLE ##TABELA02 (
	ID VARCHAR(10),
	NOME VARCHAR(10)
)

INSERT INTO ##TABELA02
VALUES ('1', 'JOÃO')

SELECT * FROM ##TABELA02


/* Desafio */
DECLARE @NUMERO_ANTERIOR2 INT;
DECLARE @NUMERO_ANTERIOR1 INT;
DECLARE @NUMERO_ATUAL INT;
DECLARE @SEQUENCIA INT;
DECLARE @CONTADOR_SEQUENCIA INT;
DECLARE @TABELA TABLE (SEQUENCIA INT, VALOR INT);

SET @SEQUENCIA = 44;
SET @CONTADOR_SEQUENCIA = 3;

SET @NUMERO_ANTERIOR2 = 0;
SET @NUMERO_ANTERIOR1 = 1;
INSERT INTO @TABELA VALUES (1,0);
INSERT INTO @TABELA VALUES (2,1);
WHILE @CONTADOR_SEQUENCIA <= @SEQUENCIA
BEGIN
   SET @NUMERO_ATUAL = @NUMERO_ANTERIOR2 + @NUMERO_ANTERIOR1;
   INSERT INTO @TABELA VALUES (@CONTADOR_SEQUENCIA,@NUMERO_ATUAL);
   SET  @NUMERO_ANTERIOR2 = @NUMERO_ANTERIOR1;
   SET @NUMERO_ANTERIOR1 = @NUMERO_ATUAL;
   SET @CONTADOR_SEQUENCIA = @CONTADOR_SEQUENCIA + 1;
END;
SELECT * FROM @TABELA;
