SELECT NOME,
		CHARINDEX(' ', NOME) [Posição do primeiro espaço em branco],
		SUBSTRING(NOME, 1, CHARINDEX(' ', NOME) - 1) [Posição 1 até o espaço em branco]
FROM [SUCOS_VENDAS].dbo.[TABELA DE CLIENTES]

--SELECT * FROM [SUCOS_VENDAS].dbo.[TABELA DE CLIENTES]

DECLARE @NOME VARCHAR(50),
		@CPF VARCHAR(11),
		@SAIDA VARCHAR(100)
SET @CPF = '1471156710'
SELECT @NOME = NOME
FROM [SUCOS_VENDAS].dbo.[TABELA DE CLIENTES]
WHERE CPF = @CPF
SET @SAIDA = 'Cliente ' + @NOME + ', cujo CPF é ' + @CPF + ', corresponde a ' + SUBSTRING(@NOME, 1, CHARINDEX(' ', @NOME) - 1)
PRINT @SAIDA


/* Desafio */
DECLARE @CPF_CNPJ VARCHAR(15),
		@DATA_NASCIMENTO DATE,
		@IDADE INT
SET @CPF_CNPJ = '1471156710';
SELECT @DATA_NASCIMENTO = [DATA DE NASCIMENTO] 
FROM [SUCOS_VENDAS].dbo.[TABELA DE CLIENTES] 
WHERE CPF = @CPF_CNPJ;
PRINT DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());