--IF OBJECT_ID('TABELA DE NUMEROS', 'U') IS NOT NULL
--	DROP TABLE [TABELA DE NUMEROS]

--CREATE TABLE [TABELA DE NUMEROS] (
--	[NUMERO] INT,
--	[STATUS] VARCHAR(20)
--)

DECLARE @NUM_INICIAL_SEQUENCIA INT,
		@NUM_FINAL_SEQUENCIA INT,
		@TESTE_NF INT
DECLARE @TABELA_DE_NUMEROS TABLE (
	[NUMERO] INT,
	[STATUS] VARCHAR(20)
)

CREATE TABLE #TABELA_DE_NUMEROS (
	[NUMERO] INT,
	[STATUS] VARCHAR(20)
)

SET @NUM_INICIAL_SEQUENCIA = 1
SET @NUM_FINAL_SEQUENCIA = 200

SET NOCOUNT ON
WHILE @NUM_INICIAL_SEQUENCIA <= @NUM_FINAL_SEQUENCIA
	BEGIN 
		SELECT @TESTE_NF = COUNT(*) 
		FROM [NOTAS FISCAIS] 
		WHERE NUMERO = @NUM_INICIAL_SEQUENCIA
			IF @TESTE_NF = 1
				BEGIN 
					INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS])
					VALUES (@NUM_INICIAL_SEQUENCIA, 'É nota fiscal')
					INSERT INTO #TABELA_DE_NUMEROS ([NUMERO], [STATUS])
					VALUES (@NUM_INICIAL_SEQUENCIA, 'É nota fiscal')
				END
			ELSE
				BEGIN 
					INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS])
					VALUES (@NUM_INICIAL_SEQUENCIA, 'Não é nota fiscal')
					INSERT INTO #TABELA_DE_NUMEROS ([NUMERO], [STATUS])
					VALUES (@NUM_INICIAL_SEQUENCIA, 'Não é nota fiscal')
				END
		SET @NUM_INICIAL_SEQUENCIA = @NUM_INICIAL_SEQUENCIA + 1
	END


SELECT * FROM @TABELA_DE_NUMEROS
SELECT * FROM #TABELA_DE_NUMEROS
SELECT MIN(NUMERO), MAX(NUMERO) FROM [NOTAS FISCAIS]




/* Desafio */
IF OBJECT_ID('TABELA NOTAS', 'U') IS NOT NULL
	DROP TABLE [TABELA NOTAS]

CREATE TABLE [TABELA NOTAS] (
	DATA DATE,
	NUMNOTAS INT
)

DECLARE @DATAINICIAL DATE,
		@DATAFINAL DATE,
		@NUMNOTAS INT
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'

WHILE @DATAINICIAL <= @DATAFINAL
	BEGIN 
		SELECT @NUMNOTAS = COUNT(*)
		FROM [NOTAS FISCAIS]
		WHERE DATA = @DATAINICIAL
		INSERT INTO [TABELA NOTAS] (DATA, NUMNOTAS)
		VALUES (@DATAINICIAL, @NUMNOTAS)
		SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
	END

SELECT * FROM [TABELA NOTAS]