DECLARE @LIMIT_MIN INT,
		@LIMIT_MAX INT
SET @LIMIT_MIN = 3
SET @LIMIT_MAX = 10

PRINT 'ENTRE NO LOOPING'
WHILE @LIMIT_MIN <= @LIMIT_MAX
	BEGIN
		PRINT @LIMIT_MIN
		SET @LIMIT_MIN = @LIMIT_MIN + 1
	END
	PRINT 'SAI DO LOOPING'



/* Desafio */
DECLARE @NUMNOTAS INT,
		@DATAINICIAL DATE,
		@DATAFINAL DATE
SET @DATAINICIAL = '20170101'
SET @DATAFINAL = '20170110'

WHILE @DATAINICIAL <= @DATAFINAL
	BEGIN
		SELECT @NUMNOTAS = COUNT(*)
		FROM [SUCOS_VENDAS].dbo.[NOTAS FISCAIS]
		WHERE DATA = @DATAINICIAL
		PRINT CONVERT(VARCHAR(10), @DATAINICIAL) + ' --> ' 
        + CONVERT(VARCHAR(10), @NUMNOTAS)
		SELECT @DATAINICIAL = DATEADD(DAY, 1, @DATAINICIAL)
	END