SELECT * FROM [TABELA DE CLIENTES]

-- ALTER para alterar a função
--CREATE FUNCTION enderecoCompleto (
--	@ENDERECO VARCHAR(100),
--	@BAIRRO VARCHAR(50),
--	@CIDADE VARCHAR(50),
--	@ESTADO VARCHAR(2),
--	@CEP VARCHAR(20)
--) RETURNS VARCHAR(250)
--AS
--BEGIN 
--	DECLARE @ENDERECO_COMPLETO VARCHAR(250)
--	SET @ENDERECO_COMPLETO = @ENDERECO + ' - ' + @BAIRRO + ' - ' + @CIDADE + ' - ' + @ESTADO + ' - ' + @CEP 
--	RETURN @ENDERECO_COMPLETO
--END

SELECT CPF, [dbo].[enderecoCompleto]([ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP) AS ENDERECO_COMPLETO
FROM [TABELA DE CLIENTES]