DECLARE @LIMITE_MIN INT,
		@LIMITE_MAX INT
DECLARE @TABELA_NUMEROS 
		TABLE ([NUMERO] INT, [STATUS] VARCHAR(200), [FATURAMENTO] FLOAT)
DECLARE @CONTADOR_NOTAS INT

SET @LIMITE_MIN = 1
SET @LIMITE_MAX = 100000

SET NOCOUNT ON
WHILE @LIMITE_MIN <= @LIMITE_MAX
	BEGIN
		SELECT @CONTADOR_NOTAS = COUNT(*) FROM [dbo].[NOTAS FISCAIS] WHERE NUMERO = @LIMITE_MIN
		IF @CONTADOR_NOTAS > 0
			BEGIN 
				INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS, FATURAMENTO) 
				VALUES (@LIMITE_MIN, 'É NF', [dbo].[FaturamentoNota](@LIMITE_MIN))
			END
		ELSE
			BEGIN 
				INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS, FATURAMENTO) 
				VALUES (@LIMITE_MIN, 'NÃO É NF', 0)
			END
		SET @LIMITE_MIN = @LIMITE_MIN + 1
	END

SELECT * FROM @TABELA_NUMEROS ORDER BY NUMERO
SELECT MIN(NUMERO), MAX(NUMERO) FROM [dbo].[NOTAS FISCAIS]

--SELECT NOME, BAIRRO
--FROM [TABELA DE CLIENTES]
--WHERE CIDADE = 'Rio de Janeiro'
--ORDER BY BAIRRO
--OFFSET 3 ROWS
--FETCH NEXT 2 ROWS ONLY;
---- A consulta acima lista os bairros a partir da linha 3 (OFFSET ) e apenas uma linha (FETCH NEXT).