CREATE FUNCTION enderecoCompleto2 (
	@ENDERECO VARCHAR(100),
	@BAIRRO VARCHAR(50),
	@CIDADE VARCHAR(50),
	@ESTADO VARCHAR(2),
	@CEP VARCHAR(20)
) RETURNS VARCHAR(250)
AS
BEGIN 
	DECLARE @ENDERECO_COMPLETO VARCHAR(250)
	SET @ENDERECO_COMPLETO = @ENDERECO + ' - ' + @BAIRRO + ' - ' + @CIDADE + ' - ' + @ESTADO + ' - ' + @CEP 
	RETURN @ENDERECO_COMPLETO
END


IF OBJECT_ID('enderecoCompleto2', 'FN') IS NOT NULL
DROP FUNCTION [dbo].[enderecoCompleto2]