SELECT * FROM [NOTAS FISCAIS] WHERE CPF = '7771579779'


--CREATE FUNCTION ListaNotasCliente (@CPF AS VARCHAR(11))
--RETURNS TABLE 
--AS
--RETURN SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF

SELECT COUNT(*) FROM [dbo].[ListaNotasCliente]('7771579779')