CREATE FUNCTION FaturamentoNota (@NUMERO AS INT)

RETURNS FLOAT

AS

BEGIN

	DECLARE @FATURAMENTO FLOAT
	SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO])
	FROM [ITENS NOTAS FISCAIS]
	WHERE NUMERO = @NUMERO
	RETURN @FATURAMENTO

END

-- select *, dbo.FaturamentoNota(NUMERO) from [ITENS NOTAS FISCAIS]