--SELECT CPF, NOME, [DATA DE NASCIMENTO], IDADE, DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
--FROM [TABELA DE CLIENTES]

CREATE PROCEDURE CalculaIdade
AS
BEGIN 
	UPDATE [TABELA DE CLIENTES]
	SET IDADE = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
END

EXEC [dbo].[CalculaIdade]