CREATE TABLE TAB_CHECK (
	ID INT NOT NULL,
	NOME VARCHAR(50) NULL,
	IDADE INT NULL, 
	CIDADE VARCHAR(50) NULL,

	CONSTRAINT CHK_ID CHECK (IDADE >= 18)
)

INSERT INTO TAB_CHECK
VALUES (1, 'João', 19, 'Rio de Janeiro')

INSERT INTO TAB_CHECK
VALUES (2, 'Pedro', 20, 'Rio de Janeiro')

SELECT * FROM TAB_CHECK



CREATE TABLE TAB_CHECK2 (
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50) NULL,
	IDADE INT NULL, 
	CIDADE VARCHAR(50) NULL,

	CONSTRAINT CHK_IDADE CHECK (
		(IDADE >= 18 AND CIDADE = 'Rio de Janeiro') OR (IDADE >= 16 AND CIDADE = 'São Paulo')
	) 
)

INSERT INTO TAB_CHECK2
VALUES ('João', 19, 'Rio de Janeiro')

INSERT INTO TAB_CHECK2
VALUES ('Pedro', 17, 'São Paulo')

SELECT * FROM TAB_CHECK2