CREATE TABLE TB_PADRAO (
	ID INT IDENTITY(1,1) NOT NULL,
	DESCRITOR VARCHAR(20) NULL,
	ENDERECO VARCHAR(20) NULL,
	CIDADE VARCHAR(20) DEFAULT 'Rio de Janeiro',
	DATA_CRIACAO DATE DEFAULT GETDATE()
)

INSERT INTO TB_PADRAO (DESCRITOR, ENDERECO, CIDADE)
VALUES ('Cliente X', 'Rua Projetada A', 'São Paulo')
INSERT INTO TB_PADRAO (DESCRITOR, ENDERECO, DATA_CRIACAO)
VALUES ('Cliente Y', 'Rua Projetada C', '2024-05-04')
INSERT INTO TB_PADRAO (DESCRITOR)
VALUES ('Cliente Z')

SELECT * FROM TB_PADRAO