SELECT * FROM PRODUTOS ORDER BY CODIGO
SELECT * FROM SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS ORDER BY CODIGO_DO_PRODUTO

SELECT A.CODIGO [CODIGO TBA],
		A.PRECO_LISTA [PRECO TBA],
		B.CODIGO_DO_PRODUTO [CODIGO TBB],
		B.PRECO_DE_LISTA [PRECO TBB]
FROM PRODUTOS A
	INNER JOIN SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS B
		ON A.CODIGO = B.CODIGO_DO_PRODUTO

/* DUAS FORMAR DE RODAR UPDATE (MERGE E UPDATE) */
UPDATE A
SET	A.[PRECO_LISTA] = B.PRECO_DE_LISTA
FROM PRODUTOS A
	INNER JOIN SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS B
		ON A.CODIGO = B.CODIGO_DO_PRODUTO

MERGE INTO PRODUTOS A
	USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
		ON A.CODIGO = B.CODIGO_DO_PRODUTO
WHEN MATCHED THEN UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;




SELECT A.CPF [CLIENTES],
		B.NOME [VENDEDORES],
		A.BAIRRO
FROM [dbo].[CLIENTES] A
	INNER JOIN [dbo].[VENDEDORES] B
		ON A.[BAIRRO] = B.[BAIRRO]

/* DUAS FORMAR DE RODAR UPDATE (MERGE E UPDATE) */
UPDATE A
SET A.[VOLUME_COMPRA] = A.VOLUME_COMPRA * 1.30
FROM [dbo].[CLIENTES] A
	INNER JOIN [dbo].[VENDEDORES] B
		ON A.[BAIRRO] = B.[BAIRRO]

MERGE INTO CLIENTES A
	USING VENDEDORES B
		ON A.[BAIRRO] = B.[BAIRRO]
WHEN MATCHED THEN UPDATE SET A.[VOLUME_COMPRA] = A.VOLUME_COMPRA * 1.30;