SELECT * FROM PRODUTOS WHERE SABOR = 'Manga'

UPDATE PRODUTOS
SET PRECO_LISTA = PRECO_LISTA * 1.10
WHERE SABOR = 'Manga'




SELECT DESCRITOR, 
		REPLACE(DESCRITOR, '350 ml', '550 ml'),
		TAMANHO
FROM PRODUTOS 
WHERE TAMANHO = '350 ml'

UPDATE PRODUTOS
SET DESCRITOR = REPLACE(DESCRITOR, '350 ml', '550 ml'), TAMANHO = '550 ml'
WHERE TAMANHO = '350 ml'




SELECT * FROM CLIENTES WHERE CPF = '19290992743'

UPDATE CLIENTES
SET [ENDERECO] = 'R. Jorge Emilio 23',
    [BAIRRO] = 'Santo Amaro',
    [CIDADE] = 'São Paulo',
    [ESTADO] = 'SP',
    [CEP] = '8833223'
WHERE CPF = '19290992743'